# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'historicalfilter_dock.ui'
#
# Created: Sun Jun  5 12:07:24 2016
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_historicalMenu(object):
    def setupUi(self, historicalMenu):
        historicalMenu.setObjectName(_fromUtf8("historicalMenu"))
        historicalMenu.setEnabled(True)
        historicalMenu.resize(543, 470)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(historicalMenu.sizePolicy().hasHeightForWidth())
        historicalMenu.setSizePolicy(sizePolicy)
        historicalMenu.setMinimumSize(QtCore.QSize(520, 400))
        historicalMenu.setSizeGripEnabled(False)
        self.gridLayout_3 = QtGui.QGridLayout(historicalMenu)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        spacerItem = QtGui.QSpacerItem(4, 100, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem, 0, 0, 1, 1)
        self.label_2 = QtGui.QLabel(historicalMenu)
        self.label_2.setEnabled(True)
        self.label_2.setMinimumSize(QtCore.QSize(500, 180))
        self.label_2.setMaximumSize(QtCore.QSize(500, 180))
        self.label_2.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_2.setFrameShadow(QtGui.QFrame.Plain)
        self.label_2.setLineWidth(0)
        self.label_2.setText(_fromUtf8(""))
        self.label_2.setPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/dzetsaka/img/historical_logo.jpg")))
        self.label_2.setScaledContents(True)
        self.label_2.setWordWrap(False)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_3.addWidget(self.label_2, 0, 1, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(0, 158, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem1, 0, 2, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(200, 0, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Maximum)
        self.gridLayout_3.addItem(spacerItem2, 1, 1, 1, 1)
        self.tabWidget = QtGui.QTabWidget(historicalMenu)
        self.tabWidget.setMinimumSize(QtCore.QSize(400, 200))
        self.tabWidget.setTabShape(QtGui.QTabWidget.Rounded)
        self.tabWidget.setIconSize(QtCore.QSize(25, 25))
        self.tabWidget.setElideMode(QtCore.Qt.ElideMiddle)
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.gridLayout = QtGui.QGridLayout(self.tab)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.tiffImageLabel = QtGui.QLabel(self.tab)
        self.tiffImageLabel.setMinimumSize(QtCore.QSize(130, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tiffImageLabel.setFont(font)
        self.tiffImageLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.tiffImageLabel.setObjectName(_fromUtf8("tiffImageLabel"))
        self.gridLayout.addWidget(self.tiffImageLabel, 0, 0, 1, 1)
        self.inRaster = gui.QgsMapLayerComboBox(self.tab)
        self.inRaster.setMinimumSize(QtCore.QSize(80, 0))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.inRaster.setFont(font)
        self.inRaster.setFilters(gui.QgsMapLayerProxyModel.PluginLayer|gui.QgsMapLayerProxyModel.RasterLayer)
        self.inRaster.setObjectName(_fromUtf8("inRaster"))
        self.gridLayout.addWidget(self.inRaster, 0, 1, 1, 5)
        self.tiffImageLabel_2 = QtGui.QLabel(self.tab)
        self.tiffImageLabel_2.setMinimumSize(QtCore.QSize(130, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tiffImageLabel_2.setFont(font)
        self.tiffImageLabel_2.setToolTip(_fromUtf8(""))
        self.tiffImageLabel_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.tiffImageLabel_2.setObjectName(_fromUtf8("tiffImageLabel_2"))
        self.gridLayout.addWidget(self.tiffImageLabel_2, 1, 0, 1, 1)
        self.inClosingSize = gui.QgsSpinBox(self.tab)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.inClosingSize.setFont(font)
        self.inClosingSize.setMinimum(1)
        self.inClosingSize.setMaximum(999)
        self.inClosingSize.setSingleStep(2)
        self.inClosingSize.setProperty("value", 11)
        self.inClosingSize.setObjectName(_fromUtf8("inClosingSize"))
        self.gridLayout.addWidget(self.inClosingSize, 1, 1, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(194, 40, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 1, 4, 2, 2)
        self.tiffImageLabel_3 = QtGui.QLabel(self.tab)
        self.tiffImageLabel_3.setMinimumSize(QtCore.QSize(130, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tiffImageLabel_3.setFont(font)
        self.tiffImageLabel_3.setToolTip(_fromUtf8(""))
        self.tiffImageLabel_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.tiffImageLabel_3.setObjectName(_fromUtf8("tiffImageLabel_3"))
        self.gridLayout.addWidget(self.tiffImageLabel_3, 2, 0, 1, 1)
        self.inMedianSize = gui.QgsSpinBox(self.tab)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.inMedianSize.setFont(font)
        self.inMedianSize.setMinimum(1)
        self.inMedianSize.setMaximum(999)
        self.inMedianSize.setSingleStep(2)
        self.inMedianSize.setProperty("value", 11)
        self.inMedianSize.setObjectName(_fromUtf8("inMedianSize"))
        self.gridLayout.addWidget(self.inMedianSize, 2, 1, 1, 1)
        self.tiffImageLabel_17 = QtGui.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tiffImageLabel_17.setFont(font)
        self.tiffImageLabel_17.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.tiffImageLabel_17.setObjectName(_fromUtf8("tiffImageLabel_17"))
        self.gridLayout.addWidget(self.tiffImageLabel_17, 2, 2, 1, 1)
        self.inMedianIter = gui.QgsSpinBox(self.tab)
        self.inMedianIter.setMinimumSize(QtCore.QSize(80, 25))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.inMedianIter.setFont(font)
        self.inMedianIter.setMinimum(1)
        self.inMedianIter.setMaximum(99)
        self.inMedianIter.setSingleStep(1)
        self.inMedianIter.setProperty("value", 1)
        self.inMedianIter.setObjectName(_fromUtf8("inMedianIter"))
        self.gridLayout.addWidget(self.inMedianIter, 2, 3, 1, 1)
        self.tiffImageLabel_16 = QtGui.QLabel(self.tab)
        self.tiffImageLabel_16.setMinimumSize(QtCore.QSize(130, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tiffImageLabel_16.setFont(font)
        self.tiffImageLabel_16.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.tiffImageLabel_16.setObjectName(_fromUtf8("tiffImageLabel_16"))
        self.gridLayout.addWidget(self.tiffImageLabel_16, 3, 0, 1, 1)
        self.outRaster = QtGui.QLineEdit(self.tab)
        self.outRaster.setText(_fromUtf8(""))
        self.outRaster.setObjectName(_fromUtf8("outRaster"))
        self.gridLayout.addWidget(self.outRaster, 3, 1, 1, 4)
        self.outRasterButton = QtGui.QPushButton(self.tab)
        self.outRasterButton.setMinimumSize(QtCore.QSize(25, 0))
        self.outRasterButton.setMaximumSize(QtCore.QSize(25, 16777215))
        self.outRasterButton.setAutoDefault(False)
        self.outRasterButton.setObjectName(_fromUtf8("outRasterButton"))
        self.gridLayout.addWidget(self.outRasterButton, 3, 5, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(309, 17, QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem4, 4, 0, 1, 3)
        self.runFilter = QtGui.QPushButton(self.tab)
        self.runFilter.setMinimumSize(QtCore.QSize(150, 0))
        self.runFilter.setObjectName(_fromUtf8("runFilter"))
        self.gridLayout.addWidget(self.runFilter, 4, 3, 1, 3)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.gridLayout_2 = QtGui.QGridLayout(self.tab_2)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.tiffImageLabel_12 = QtGui.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.tiffImageLabel_12.setFont(font)
        self.tiffImageLabel_12.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.tiffImageLabel_12.setObjectName(_fromUtf8("tiffImageLabel_12"))
        self.gridLayout_2.addWidget(self.tiffImageLabel_12, 0, 0, 1, 1)
        self.tiffImageLabel_13 = QtGui.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.tiffImageLabel_13.setFont(font)
        self.tiffImageLabel_13.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.tiffImageLabel_13.setObjectName(_fromUtf8("tiffImageLabel_13"))
        self.gridLayout_2.addWidget(self.tiffImageLabel_13, 1, 0, 1, 1)
        self.sieveSize = QtGui.QSpinBox(self.tab_2)
        self.sieveSize.setMaximum(999)
        self.sieveSize.setProperty("value", 5)
        self.sieveSize.setObjectName(_fromUtf8("sieveSize"))
        self.gridLayout_2.addWidget(self.sieveSize, 1, 1, 1, 1)
        self.tiffImageLabel_14 = QtGui.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.tiffImageLabel_14.setFont(font)
        self.tiffImageLabel_14.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.tiffImageLabel_14.setObjectName(_fromUtf8("tiffImageLabel_14"))
        self.gridLayout_2.addWidget(self.tiffImageLabel_14, 1, 2, 1, 1)
        spacerItem5 = QtGui.QSpacerItem(224, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem5, 1, 3, 1, 3)
        self.tiffImageLabel_18 = QtGui.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.tiffImageLabel_18.setFont(font)
        self.tiffImageLabel_18.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.tiffImageLabel_18.setObjectName(_fromUtf8("tiffImageLabel_18"))
        self.gridLayout_2.addWidget(self.tiffImageLabel_18, 2, 0, 1, 1)
        self.classNumber = QtGui.QSpinBox(self.tab_2)
        self.classNumber.setMaximum(999)
        self.classNumber.setProperty("value", 1)
        self.classNumber.setObjectName(_fromUtf8("classNumber"))
        self.gridLayout_2.addWidget(self.classNumber, 2, 1, 1, 1)
        spacerItem6 = QtGui.QSpacerItem(224, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem6, 2, 3, 1, 3)
        self.tiffImageLabel_19 = QtGui.QLabel(self.tab_2)
        self.tiffImageLabel_19.setMinimumSize(QtCore.QSize(130, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tiffImageLabel_19.setFont(font)
        self.tiffImageLabel_19.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.tiffImageLabel_19.setObjectName(_fromUtf8("tiffImageLabel_19"))
        self.gridLayout_2.addWidget(self.tiffImageLabel_19, 3, 0, 1, 1)
        self.outShp = QtGui.QLineEdit(self.tab_2)
        self.outShp.setText(_fromUtf8(""))
        self.outShp.setObjectName(_fromUtf8("outShp"))
        self.gridLayout_2.addWidget(self.outShp, 3, 1, 1, 4)
        self.outShpButton = QtGui.QPushButton(self.tab_2)
        self.outShpButton.setMinimumSize(QtCore.QSize(25, 0))
        self.outShpButton.setMaximumSize(QtCore.QSize(25, 16777215))
        self.outShpButton.setAutoDefault(False)
        self.outShpButton.setObjectName(_fromUtf8("outShpButton"))
        self.gridLayout_2.addWidget(self.outShpButton, 3, 5, 1, 1)
        spacerItem7 = QtGui.QSpacerItem(309, 17, QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem7, 4, 0, 1, 4)
        self.runPostClass = QtGui.QPushButton(self.tab_2)
        self.runPostClass.setMinimumSize(QtCore.QSize(150, 0))
        self.runPostClass.setObjectName(_fromUtf8("runPostClass"))
        self.gridLayout_2.addWidget(self.runPostClass, 4, 4, 1, 2)
        self.inFilteredStep3 = gui.QgsMapLayerComboBox(self.tab_2)
        self.inFilteredStep3.setMinimumSize(QtCore.QSize(0, 30))
        self.inFilteredStep3.setFilters(gui.QgsMapLayerProxyModel.PluginLayer|gui.QgsMapLayerProxyModel.RasterLayer)
        self.inFilteredStep3.setObjectName(_fromUtf8("inFilteredStep3"))
        self.gridLayout_2.addWidget(self.inFilteredStep3, 0, 1, 1, 5)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.gridLayout_4 = QtGui.QGridLayout(self.tab_3)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.textBrowser = QtGui.QTextBrowser(self.tab_3)
        self.textBrowser.setOpenExternalLinks(True)
        self.textBrowser.setObjectName(_fromUtf8("textBrowser"))
        self.gridLayout_4.addWidget(self.textBrowser, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.gridLayout_3.addWidget(self.tabWidget, 2, 0, 1, 3)
        spacerItem8 = QtGui.QSpacerItem(200, 0, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem8, 3, 1, 1, 1)

        self.retranslateUi(historicalMenu)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(historicalMenu)

    def retranslateUi(self, historicalMenu):
        historicalMenu.setWindowTitle(_translate("historicalMenu", "Historical Map | dzetska", None))
        self.tiffImageLabel.setText(_translate("historicalMenu", "Image to filter :", None))
        self.tiffImageLabel_2.setText(_translate("historicalMenu", "closing size :", None))
        self.tiffImageLabel_3.setText(_translate("historicalMenu", "median size :", None))
        self.tiffImageLabel_17.setText(_translate("historicalMenu", "iteration :", None))
        self.tiffImageLabel_16.setText(_translate("historicalMenu", "Save as :", None))
        self.outRaster.setPlaceholderText(_translate("historicalMenu", "Leave empty for temporary file...", None))
        self.outRasterButton.setText(_translate("historicalMenu", "...", None))
        self.runFilter.setText(_translate("historicalMenu", "Filter image", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("historicalMenu", "Filtering", None))
        self.tiffImageLabel_12.setText(_translate("historicalMenu", "Classified image :", None))
        self.tiffImageLabel_13.setText(_translate("historicalMenu", "Sieve size :", None))
        self.tiffImageLabel_14.setText(_translate("historicalMenu", "(in pixels)", None))
        self.tiffImageLabel_18.setText(_translate("historicalMenu", "Class number :", None))
        self.tiffImageLabel_19.setText(_translate("historicalMenu", "Save as :", None))
        self.outShp.setPlaceholderText(_translate("historicalMenu", "Leave empty for temporary file...", None))
        self.outShpButton.setText(_translate("historicalMenu", "...", None))
        self.runPostClass.setText(_translate("historicalMenu", "Finish classification", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("historicalMenu", "Post-Classification", None))
        self.textBrowser.setHtml(_translate("historicalMenu", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Sans Serif\'; font-size:12pt; font-weight:600;\">Historical Map process for dzetsaka</span></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Sans Serif\'; font-size:12pt; font-weight:600; text-decoration: underline; color:#0057ae;\"><br /></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Sans Serif\'; font-size:9pt;\">Historical Map is a process developped by Pierre-Alexis Herrault for automatic detection and vectorisation of forest from old maps.</span></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Sans Serif\'; font-size:9pt;\"><br /></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Sans Serif\'; font-size:9pt;\">Initially developped as a solo plugin, it has been integrated in dzetsaka.</span></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Sans Serif\'; font-size:9pt;\"><br /></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Sans Serif\'; font-size:9pt;\">You can find more information for this tool on the github page of </span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a href=\"https://github.com/lennepkade/HistoricalMap\"><span style=\" text-decoration: underline; color:#0000ff;\">Historical Map plugin for Qgis.</span></a></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Sans Serif\'; font-size:9pt;\"><br /></p></body></html>", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("historicalMenu", "Help", None))

from qgis import gui
