# Form implementation generated from reading ui file 'ui\settings_dock.ui'
#
# Created by: PyQt6 UI code generator 6.10.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from qgis.PyQt import QtCore, QtGui, QtWidgets

try:
    _ALIGN_RIGHT = QtCore.Qt.AlignRight
    _ALIGN_TRAILING = QtCore.Qt.AlignTrailing
    _ALIGN_VCENTER = QtCore.Qt.AlignVCenter
    _ITEM_LABEL = QtWidgets.QFormLayout.LabelRole
    _ITEM_FIELD = QtWidgets.QFormLayout.FieldRole
except AttributeError:
    _ALIGN_RIGHT = QtCore.Qt.AlignmentFlag.AlignRight
    _ALIGN_TRAILING = QtCore.Qt.AlignmentFlag.AlignTrailing
    _ALIGN_VCENTER = QtCore.Qt.AlignmentFlag.AlignVCenter
    _ITEM_LABEL = QtWidgets.QFormLayout.ItemRole.LabelRole
    _ITEM_FIELD = QtWidgets.QFormLayout.ItemRole.FieldRole


class Ui_settingsDock(object):
    def setupUi(self, settingsDock):
        settingsDock.setObjectName("settingsDock")
        settingsDock.resize(317, 202)
        settingsDock.setMinimumSize(QtCore.QSize(317, 202))
        settingsDock.setMaximumSize(QtCore.QSize(600, 600))
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.formLayout = QtWidgets.QFormLayout(self.dockWidgetContents)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(parent=self.dockWidgetContents)
        self.label.setAlignment(_ALIGN_RIGHT | _ALIGN_TRAILING | _ALIGN_VCENTER)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, _ITEM_LABEL, self.label)
        self.selectClassifier = QtWidgets.QComboBox(parent=self.dockWidgetContents)
        self.selectClassifier.setObjectName("selectClassifier")
        self.selectClassifier.addItem("")
        self.selectClassifier.addItem("")
        self.selectClassifier.addItem("")
        self.selectClassifier.addItem("")
        self.selectClassifier.addItem("")
        self.selectClassifier.addItem("")
        self.selectClassifier.addItem("")
        self.selectClassifier.addItem("")
        self.selectClassifier.addItem("")
        self.selectClassifier.addItem("")
        self.selectClassifier.addItem("")
        self.selectClassifier.addItem("")
        self.formLayout.setWidget(0, _ITEM_FIELD, self.selectClassifier)
        self.label_2 = QtWidgets.QLabel(parent=self.dockWidgetContents)
        self.label_2.setAlignment(_ALIGN_RIGHT | _ALIGN_TRAILING | _ALIGN_VCENTER)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, _ITEM_LABEL, self.label_2)
        self.classSuffix = QtWidgets.QLineEdit(parent=self.dockWidgetContents)
        self.classSuffix.setObjectName("classSuffix")
        self.formLayout.setWidget(1, _ITEM_FIELD, self.classSuffix)
        self.label_3 = QtWidgets.QLabel(parent=self.dockWidgetContents)
        self.label_3.setAlignment(_ALIGN_RIGHT | _ALIGN_TRAILING | _ALIGN_VCENTER)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, _ITEM_LABEL, self.label_3)
        self.classPrefix = QtWidgets.QLineEdit(parent=self.dockWidgetContents)
        self.classPrefix.setText("")
        self.classPrefix.setObjectName("classPrefix")
        self.formLayout.setWidget(2, _ITEM_FIELD, self.classPrefix)
        self.label_4 = QtWidgets.QLabel(parent=self.dockWidgetContents)
        self.label_4.setAlignment(_ALIGN_RIGHT | _ALIGN_TRAILING | _ALIGN_VCENTER)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(3, _ITEM_LABEL, self.label_4)
        self.maskSuffix = QtWidgets.QLineEdit(parent=self.dockWidgetContents)
        self.maskSuffix.setText("")
        self.maskSuffix.setObjectName("maskSuffix")
        self.formLayout.setWidget(3, _ITEM_FIELD, self.maskSuffix)
        self.label_5 = QtWidgets.QLabel(parent=self.dockWidgetContents)
        self.label_5.setAlignment(_ALIGN_RIGHT | _ALIGN_TRAILING | _ALIGN_VCENTER)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(4, _ITEM_LABEL, self.label_5)
        self.selectProviders = QtWidgets.QComboBox(parent=self.dockWidgetContents)
        self.selectProviders.setObjectName("selectProviders")
        self.selectProviders.addItem("")
        self.selectProviders.addItem("")
        self.formLayout.setWidget(4, _ITEM_FIELD, self.selectProviders)
        settingsDock.setWidget(self.dockWidgetContents)

        self.retranslateUi(settingsDock)
        QtCore.QMetaObject.connectSlotsByName(settingsDock)

    def retranslateUi(self, settingsDock):
        _translate = QtCore.QCoreApplication.translate
        settingsDock.setWindowTitle(_translate("settingsDock", "dzetsaka : settings panel"))
        self.label.setText(_translate("settingsDock", "Classifier :"))
        self.selectClassifier.setItemText(0, _translate("settingsDock", "Gaussian Mixture Model"))
        self.selectClassifier.setItemText(1, _translate("settingsDock", "Random Forest"))
        self.selectClassifier.setItemText(2, _translate("settingsDock", "Support Vector Machine"))
        self.selectClassifier.setItemText(3, _translate("settingsDock", "K-Nearest Neighbors"))
        self.selectClassifier.setItemText(4, _translate("settingsDock", "XGBoost"))
        self.selectClassifier.setItemText(5, _translate("settingsDock", "LightGBM"))
        self.selectClassifier.setItemText(6, _translate("settingsDock", "CatBoost"))
        self.selectClassifier.setItemText(7, _translate("settingsDock", "Extra Trees"))
        self.selectClassifier.setItemText(8, _translate("settingsDock", "Gradient Boosting Classifier"))
        self.selectClassifier.setItemText(9, _translate("settingsDock", "Logistic Regression"))
        self.selectClassifier.setItemText(10, _translate("settingsDock", "Gaussian Naive Bayes"))
        self.selectClassifier.setItemText(11, _translate("settingsDock", "Multi-layer Perceptron"))
        self.label_2.setText(_translate("settingsDock", "Temp suffix :"))
        self.label_3.setText(_translate("settingsDock", "Temp prefix :"))
        self.label_4.setText(_translate("settingsDock", "Mask suffix :"))
        self.label_5.setText(_translate("settingsDock", "Providers : "))
        self.selectProviders.setItemText(0, _translate("settingsDock", "Standard"))
        self.selectProviders.setItemText(1, _translate("settingsDock", "Advanced"))
