# Form implementation generated from reading ui file 'ui\welcome.ui'
#
# Created by: PyQt6 UI code generator 6.10.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from qgis.PyQt import QtCore, QtGui, QtWidgets

try:
    _ALIGN_HCENTER = QtCore.Qt.AlignHCenter
    _ALIGN_TOP = QtCore.Qt.AlignTop
    _POLICY_PREF = QtWidgets.QSizePolicy.Preferred
    _POLICY_FIXED = QtWidgets.QSizePolicy.Fixed
    _POLICY_MIN = QtWidgets.QSizePolicy.Minimum
except AttributeError:
    _ALIGN_HCENTER = QtCore.Qt.AlignmentFlag.AlignHCenter
    _ALIGN_TOP = QtCore.Qt.AlignmentFlag.AlignTop
    _POLICY_PREF = QtWidgets.QSizePolicy.Policy.Preferred
    _POLICY_FIXED = QtWidgets.QSizePolicy.Policy.Fixed
    _POLICY_MIN = QtWidgets.QSizePolicy.Policy.Minimum


class Ui_DockWidget(object):
    def setupUi(self, DockWidget):
        DockWidget.setObjectName("DockWidget")
        DockWidget.resize(513, 387)
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setEnabled(True)
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.gridLayout = QtWidgets.QGridLayout(self.dockWidgetContents)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(parent=self.dockWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(_POLICY_PREF, _POLICY_FIXED)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setAcceptDrops(True)
        self.label.setAutoFillBackground(False)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/plugins/dzetsaka/img/parcguyane.jpg"))
        self.label.setScaledContents(False)
        self.label.setAlignment(_ALIGN_HCENTER | _ALIGN_TOP)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(478, 10, _POLICY_MIN, _POLICY_FIXED)
        self.gridLayout.addItem(spacerItem, 1, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(parent=self.dockWidgetContents)
        self.label_2.setAutoFillBackground(True)
        self.label_2.setWordWrap(True)
        self.label_2.setOpenExternalLinks(True)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        DockWidget.setWidget(self.dockWidgetContents)

        self.retranslateUi(DockWidget)
        QtCore.QMetaObject.connectSlotsByName(DockWidget)

    def retranslateUi(self, DockWidget):
        _translate = QtCore.QCoreApplication.translate
        DockWidget.setWindowTitle(_translate("DockWidget", "Welcome to dzetsaka"))
        self.label_2.setText(_translate("DockWidget", "<html><head/><body><p><span style=\" font-weight:600;\">Thanks for installing dzetsaka.</span></p><p>For documentation and updates, visit <a href=\"https://github.com/nkarasiak/dzetsaka\"><span style=\" font-weight:600; text-decoration: underline; color:#046c08;\">https://github.com/nkarasiak/dzetsaka</span></a>.</p><p>You can also download a sample dataset to test and understand how dzetsaka works: <a href=\"https://github.com/lennepkade/dzetsaka/archive/docs.zip\"><span style=\" font-weight:600; text-decoration: underline; color:#046c08;\">https://github.com/lennepkade/dzetsaka/archive/docs.zip</span></a>.</p><p>Have fun,<br/>Nicolas Karasiak</p></body></html>"))
